- name: Update apt cache
  apt:
    update_cache: true

- name: Install packages
  apt:
    name:
      - git
      - stow
      - tmux
    state: present

- name: Restow dotfiles
  command: stow --restow -t {{ ansible_user_dir }} */
  args:
    chdir: "{{ ansible_user_dir }}/machine-setup/dotfiles"
